In [6]:
import string
from collections import Counter
from pprint import pprint

# Data & numerical computing
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt

import re

# NLP
import nltk
nltk.download('wordnet')

# Utilities
import tqdm as tq
from tqdm import tqdm

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\yuliy\AppData\Roaming\nltk_data...

## Stemming

In [7]:
words = ['playing', 'loved', 'ran', 'river', 'friendships',
         'misunderstanding', 'trouble', 'troubling']

stemmers = {
    'LancasterStemmer': nltk.stem.LancasterStemmer(),
    'PorterStemmer': nltk.stem.PorterStemmer(),
    'RegexpStemmer': nltk.stem.RegexpStemmer('ing$|s$|e$|able$'),
    'SnowballStemmer': nltk.stem.SnowballStemmer('english')
}

In [8]:
matrix = []

for word in words:
    row = []
    for stemmer in stemmers:
        stem = stemmers[stemmer]
        row.append(stem.stem(word))

    matrix.append(row)

comparison = pd.DataFrame(matrix, index=words, columns=stemmers.keys())

In [9]:
comparison

,LancasterStemmer,PorterStemmer,RegexpStemmer,SnowballStemmer
playing,play,play,play,play
loved,lov,love,loved,love
ran,ran,ran,ran,ran
river,riv,river,river,river
friendships,friend,friendship,friendship,friendship
misunderstanding,misunderstand,misunderstand,misunderstand,misunderstand
trouble,troubl,troubl,troubl,troubl
troubling,troubl,troubl,troubl,troubl

## Lemmatization

In [10]:
wordnet = nltk.stem.WordNetLemmatizer()

results_n = [wordnet.lemmatize(word, 'n') for word in words]
results_v = [wordnet.lemmatize(word, 'v') for word in words]

In [11]:
comparison['WordNetLemmatizer Noun'] = results_n
comparison['WordNetLemmatizer Verb'] = results_v

comparison

,LancasterStemmer,PorterStemmer,RegexpStemmer,SnowballStemmer,WordNetLemmatizer Noun,WordNetLemmatizer Verb
playing,play,play,play,play,playing,play
loved,lov,love,loved,love,loved,love
ran,ran,ran,ran,ran,ran,run
river,riv,river,river,river,river,river
friendships,friend,friendship,friendship,friendship,friendship,friendships
misunderstanding,misunderstand,misunderstand,misunderstand,misunderstand,misunderstanding,misunderstand
trouble,troubl,troubl,troubl,troubl,trouble,trouble
troubling,troubl,troubl,troubl,troubl,troubling,trouble